package service

import (
	"context"
	"os"
)

// FileWriter defines the interface for writing files.
// Implementations should handle creating parent directories if necessary.
type FileWriter interface {
	WriteFile(path string, content []byte, perm os.FileMode) error
}

// DirectoryManager defines the interface for managing directories.
// Implementations should handle creating parent directories if necessary and checking existence.
type DirectoryManager interface {
	CreateDir(path string, perm os.FileMode) error
	Exists(path string) (bool, error)
}

// LLMProvider defines the interface for LLM-based content generation.
type LLMProvider interface {
	GenerateContext(ctx context.Context, request GenerationRequest) (*GenerationResponse, error)

	// EvaluatePrompt sends a single one-shot prompt and returns the response
	// text plus token counts. Used by lifecycle commands that need a single
	// prompt→response cycle (e.g. `codify audit --with-llm`) instead of the
	// multi-file template-driven flow of GenerateContext.
	//
	// Implementations record usage just like GenerateContext does — the
	// caller does not need to know about the recorder.
	EvaluatePrompt(ctx context.Context, request EvaluationRequest) (*EvaluationResponse, error)
}

// TemplateLoader defines the interface for loading template guides from disk.
type TemplateLoader interface {
	LoadAll() ([]TemplateGuide, error)
}

// GenerationRequest represents a request to generate context files via LLM.
type GenerationRequest struct {
	ProjectDescription string
	TemplateGuides     []TemplateGuide
	Language           string
	ProjectType        string
	Architecture       string
	Locale             string // Output language: "en", "es", etc.
	ExistingContext    string // For spec mode: content of existing CONTEXT.md + AGENTS.md
	Mode               string // "generate" (default), "analyze", "spec", "workflows", or "workflow-skills"
	Target             string // For workflows mode: target ecosystem ("claude", "antigravity")
	ProjectContext     string // For personalized workflows: project description/context

	// SDDStandardHints, when non-empty, is appended to the spec system
	// prompt by the LLM provider. Sourced from the active SpecStandard
	// adapter — empty for OpenSpec (its conventions are already the
	// implicit base of the prompt), non-empty for Spec-Kit and other
	// standards that need to override default expectations.
	SDDStandardHints string
}

// TemplateGuide represents a structural template used as a guide for the LLM.
//
// OutputFileName, when non-empty, takes precedence over the global
// fileOutputNames map maintained in infrastructure/llm. This allows callers
// (notably the spec command, which dispatches per active SpecStandard) to
// override the canonical file name without polluting the global map.
//
// Use cases:
//   - OpenSpec wants `spec` → "SPEC.md".
//   - Spec-Kit wants `spec` → "spec.md" (lowercase, per-feature dir).
//
// When OutputFileName is empty, FileOutputName falls back to the global map
// (current behavior for context, skills, workflows guides which do not vary
// by SpecStandard).
type TemplateGuide struct {
	Name           string // "agents", "context", "interactions", "constitution", "spec", "plan", "tasks"
	Content        string
	OutputFileName string // optional override for the file the LLM should produce
}

// GeneratedFile represents a single file generated by the LLM.
type GeneratedFile struct {
	Name    string // "AGENTS.md", "CONTEXT.md", etc.
	Content string
}

// GenerationResponse represents the LLM's response with generated files and metadata.
type GenerationResponse struct {
	Files     []GeneratedFile
	Model     string
	TokensIn  int
	TokensOut int
}

// EvaluationRequest is a one-shot prompt evaluation. Used by lifecycle
// commands (audit --with-llm) that need a single response instead of the
// multi-file flow of GenerationRequest.
type EvaluationRequest struct {
	SystemPrompt string
	UserPrompt   string
	Command      string // for usage tracking ("audit", etc.)
	MaxTokens    int    // optional; provider applies a sensible default if 0

	// CacheableSystem signals that the SystemPrompt is stable across
	// successive calls (e.g. multiple files audited or enriched in the same
	// session) and should be marked for prompt caching when the underlying
	// provider supports it. Anthropic uses cache_control ephemeral; Gemini
	// ignores the flag (its caching API has a 4k-token minimum that most
	// of our system prompts do not meet).
	CacheableSystem bool

	// Prefill seeds the assistant turn so the response can only continue from
	// it — e.g. "[" for callers that parse a JSON array, eliminating prose
	// preambles and markdown fences at the source. Providers that support it
	// (Anthropic) prepend the prefill back to the returned Text; providers
	// that do not (Gemini) ignore the field, so callers must keep their
	// defensive parsing. Must not end in whitespace (the API rejects it).
	// Ignored when OutputSchema is set (the two are mutually exclusive).
	Prefill string

	// OutputSchema, when non-nil, constrains the response to this JSON Schema
	// via the provider's native structured-output feature (Anthropic
	// output_config.format; Gemini responseSchema + responseMimeType). The
	// returned Text is then guaranteed to be schema-valid JSON, so callers can
	// json.Unmarshal it directly. The schema's top level must be an object.
	// Requires a model that supports structured outputs (codify's default
	// claude-sonnet-4-6 does); unsupported models surface an explicit API
	// error rather than degrading silently.
	OutputSchema map[string]any
}

// EvaluationResponse contains the raw text output of a one-shot prompt
// evaluation plus token usage. The caller is responsible for parsing the
// text (e.g. JSON) — providers do not interpret content.
type EvaluationResponse struct {
	Text      string
	Model     string
	TokensIn  int
	TokensOut int
}
