package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	root "github.com/jorelcb/codify"
	"github.com/jorelcb/codify/internal/application/command"
	"github.com/jorelcb/codify/internal/application/dto"
	domainservice "github.com/jorelcb/codify/internal/domain/service"
	"github.com/jorelcb/codify/internal/infrastructure/config"
	"github.com/jorelcb/codify/internal/infrastructure/filesystem"
	"github.com/jorelcb/codify/internal/infrastructure/llm"
	"github.com/jorelcb/codify/internal/infrastructure/sdd"
	infratemplate "github.com/jorelcb/codify/internal/infrastructure/template"
)

// resolveSpecStandard aplica la precedencia documentada en ADR-0011 para
// elegir el SpecStandard activo:
//
//  1. flagValue — `--sdd-standard` en la línea de comandos
//  2. project config (.codify/config.yml > sdd_standard)
//  3. user config (~/.codify/config.yml > sdd_standard)
//  4. built-in default (spec-kit)
//
// El registry resuelve los IDs contra los adapters disponibles. Si el ID en
// cualquiera de los niveles no existe, falla con error explícito (preferimos
// fallar a fallback silencioso a un standard que el usuario no eligió).
//
// Las capas user+project ya vienen mergeadas en effective.SDDStandard porque
// el repository.LoadEffective hace ese merge — basta con leer ese campo y
// dejarlo competir contra el flag y el default.
func resolveSpecStandard(flagValue string) (domainservice.SpecStandard, error) {
	registry := sdd.NewDefaultRegistry()

	repo := config.NewRepository()
	effective, err := repo.LoadEffective()
	if err != nil {
		return nil, fmt.Errorf("load effective config: %w", err)
	}

	// effective.SDDStandard ya combina user y project — Resolve solo necesita
	// el flag explícito y el merged value, en ese orden de prioridad.
	return registry.Resolve(flagValue, effective.SDDStandard, "")
}

// Los helpers de plantillas de spec (ruta, mapping y output names) viven en el
// paquete sdd (SpecTemplatePath / SpecTemplateMapping / ApplySpecOutputNames)
// para que CLI y MCP usen exactamente la misma ruta y no deriven — la regresión
// de v3.0.0 fue precisamente una ruta duplicada y desincronizada.

// slugifyFeatureID convierte un projectName en un slug seguro para
// filesystem (lowercase, ASCII, guiones para espacios y caracteres
// especiales). Es el feature/capability id que llena el token {feature} en
// el Dir de cada artefacto (specs/<feature>/, openspec/specs/<capability>/).
//
// Heurística mínima: si el nombre ya es lowercase + alfanuméricos +
// guiones, se devuelve tal cual. Si tiene mayúsculas o caracteres no-safe,
// se transforma. No hace transliteración Unicode — proyectos con nombres
// que dependan de eso pueden pasar --feature-id explícito en el futuro.
func slugifyFeatureID(name string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range name {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9':
			b.WriteRune(r)
			prevDash = false
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + ('a' - 'A'))
			prevDash = false
		case r == '-' || r == '_':
			b.WriteRune('-')
			prevDash = true
		default:
			if !prevDash {
				b.WriteRune('-')
				prevDash = true
			}
		}
	}
	out := strings.Trim(b.String(), "-")
	if out == "" {
		return "feature"
	}
	return out
}

// specParams groups all parameters for the spec command.
type specParams struct {
	fromContext string
	output      string
	model       string
	locale      string
	sddStandard string // ADR-0011 — empty = use config/default precedence
}

// NewSpecCmd creates the spec command
func NewSpecCmd() *cobra.Command {
	var p specParams

	cmd := &cobra.Command{
		Use:   "spec <project-name>",
		Short: "Generate SDD specification files from existing context",
		Long: `Generate spec-driven development files from previously generated context.

The set of files and their layout depend on the active SDD standard. Default
is GitHub Spec-Kit, which writes per-feature artifacts under specs/<feature-id>/
(spec.md with prioritized user stories, plan.md, tasks.md) plus a project-level
constitution at .specify/memory/constitution.md.

OpenSpec is also supported: it writes the real OpenSpec structure —
openspec/project.md plus openspec/specs/<capability>/spec.md with
'### Requirement:' / '#### Scenario:' (GIVEN/WHEN/THEN) blocks.

Pick the active standard with --sdd-standard (precedence: flag >
.codify/config.yml > ~/.codify/config.yml > built-in default 'spec-kit'). The
feature/capability id defaults to a slugified projectName.

See ADR-0011 and 'docs/command-reference.md' for details.

Requires existing context generated by the 'generate' command.
Requires ANTHROPIC_API_KEY (for Claude) or GEMINI_API_KEY (for Gemini) environment variable.

When run in a terminal, interactive menus guide you through options not provided via flags.

Examples:
  # Generate specs from context in current directory
  codify spec my-api --from-context .

  # Generate specs to a custom directory
  codify spec my-api --from-context ./context-dir/ --output ./specs-dir/

  # With custom model
  codify spec my-api --from-context . --model claude-sonnet-4-6`,
		Args: cobra.ExactArgs(1),
		RunE: func(cmd *cobra.Command, args []string) error {
			explicit := make(map[string]bool)
			cmd.Flags().Visit(func(f *pflag.Flag) {
				explicit[f.Name] = true
			})

			return runSpecInteractive(args[0], p, explicit)
		},
	}

	cmd.Flags().StringVar(&p.fromContext, "from-context", "", "Path to existing context directory (required; prompted in interactive mode)")
	cmd.Flags().StringVarP(&p.output, "output", "o", "", "Output directory (default: same as --from-context)")
	cmd.Flags().StringVarP(&p.model, "model", "m", "", "LLM model (default: claude-sonnet-4-6, or gemini-3.1-pro-preview)")
	cmd.Flags().StringVar(&p.locale, "locale", defaultLocale, "Output language: en (English) or es (Spanish)")
	cmd.Flags().StringVar(&p.sddStandard, "sdd-standard", "", "SDD standard: spec-kit (default) or openspec. Overrides project/user config.")

	return cmd
}

func runSpecInteractive(projectName string, p specParams, explicit map[string]bool) error {
	interactive := isInteractive()
	var err error

	// 1. Resolve from-context (required, but prompt in interactive mode).
	if p.fromContext == "" && interactive {
		p.fromContext, err = promptInput("Path to existing context directory", ".")
		if err != nil {
			return err
		}
	}
	if p.fromContext == "" {
		return fmt.Errorf("--from-context is required (use the flag or run interactively)")
	}
	// Best-effort heuristic: warn if the directory does not contain AGENTS.md or
	// CONTEXT.md, since spec generation has nothing to anchor on otherwise.
	hasContext := false
	for _, name := range []string{"AGENTS.md", "CONTEXT.md"} {
		if _, statErr := os.Stat(filepath.Join(p.fromContext, name)); statErr == nil {
			hasContext = true
			break
		}
	}
	if !hasContext {
		fmt.Fprintf(os.Stderr, "warning: %s does not appear to contain AGENTS.md or CONTEXT.md — spec generation may produce [DEFINE] markers\n", p.fromContext)
	}

	// 2. Resolve model
	if !explicit["model"] && interactive {
		p.model, err = promptModel()
		if err != nil {
			return err
		}
	}

	// 3. Resolve locale
	if !explicit["locale"] && interactive {
		p.locale, err = promptLocale()
		if err != nil {
			return err
		}
	}

	// 4. Resolve output
	if !explicit["output"] && interactive {
		defaultOutput := p.fromContext
		if defaultOutput == "" {
			defaultOutput = "."
		}
		p.output, err = promptInput("Output directory", defaultOutput)
		if err != nil {
			return err
		}
	}

	return runSpec(projectName, p.fromContext, p.output, p.model, p.locale, p.sddStandard)
}

func runSpec(projectName, fromContext, output, model, locale, sddStandardFlag string) error {
	if output == "" {
		output = fromContext
	}
	ctx := context.Background()

	// 1. Resolve API key for the selected provider
	apiKey, err := llm.ResolveAPIKey(model)
	if err != nil {
		return err
	}

	// 2. Read existing context files
	contextReader := filesystem.NewContextReader()
	existingContext, err := contextReader.ReadExistingContext(fromContext)
	if err != nil {
		return fmt.Errorf("failed to read existing context: %w", err)
	}

	// 3. Resolve active SDD standard via precedence (flag > project > user > default)
	//    and load its spec templates from templates/{locale}/sdd/{TemplateDir}/spec/.
	standard, err := resolveSpecStandard(sddStandardFlag)
	if err != nil {
		return err
	}
	templateLoader := infratemplate.NewFileSystemTemplateLoaderWithMapping(root.TemplatesFS, sdd.SpecTemplatePath(locale, standard), sdd.SpecTemplateMapping(standard))
	guides, err := templateLoader.LoadAll()
	if err != nil {
		return fmt.Errorf("failed to load spec templates for standard %q: %w", standard.ID(), err)
	}

	// 3b. Augment guides with the adapter's per-standard output file names.
	//     Required because the same guide name (e.g., "spec") maps to
	//     "SPEC.md" in OpenSpec but "spec.md" in Spec-Kit.
	guides = sdd.ApplySpecOutputNames(guides, standard)

	// 4. Initialize LLM provider
	provider, err := llm.NewProvider(ctx, model, apiKey, os.Stdout)
	if err != nil {
		return fmt.Errorf("failed to create LLM provider: %w", err)
	}

	// 5. Initialize infrastructure
	fileWriter := filesystem.NewFileWriter()
	dirManager := filesystem.NewDirectoryManager()

	// 6. Create command
	specCmd := command.NewGenerateSpecCommand(provider, fileWriter, dirManager)

	// 7. Build config. FeatureID is the feature/capability slug substituted for
	//    the {feature} token in each artifact's directory (Spec-Kit:
	//    specs/<feature>/; OpenSpec: openspec/specs/<capability>/). Default is
	//    the project name slugified to a filesystem-safe form.
	featureID := slugifyFeatureID(projectName)
	config := &dto.SpecConfig{
		ProjectName:     projectName,
		FromContextPath: fromContext,
		OutputPath:      output,
		Model:           model,
		Locale:          locale,
		FeatureID:       featureID,
		StandardID:      standard.ID(),
		StandardHints:   standard.SystemPromptHints(locale),
		Artifacts:       standard.BootstrapArtifacts(),
	}

	// 8. Show progress
	fmt.Printf("Generating specs for: %s\n", projectName)
	fmt.Printf("  From context:  %s\n", fromContext)
	fmt.Printf("  Model:         %s\n", llm.DefaultModel(model))
	fmt.Printf("  Locale:        %s\n", locale)
	fmt.Printf("  SDD standard:  %s\n", standard.DisplayName())
	if aw, ok := standard.(interface{ AlignedWith() string }); ok {
		fmt.Printf("  Aligned with:  %s\n", aw.AlignedWith())
	}
	fmt.Printf("  Feature ID:    %s\n", featureID)
	fmt.Println()
	fmt.Println("Generating spec files via LLM API...")

	// 9. Execute
	result, err := specCmd.Execute(ctx, config, existingContext, guides)
	if err != nil {
		return fmt.Errorf("spec generation failed: %w", err)
	}

	// 10. Update AGENTS.md with specs references
	if err := updateAgentsWithSpecsRef(output, locale, standard, featureID); err != nil {
		fmt.Fprintf(os.Stderr, "Warning: could not update AGENTS.md with specs reference: %v\n", err)
	}

	// 11. Show results
	fmt.Println()
	fmt.Println("Spec files generated successfully!")
	fmt.Printf("  Output: %s\n", result.OutputPath)
	fmt.Printf("  Model: %s\n", result.Model)
	fmt.Printf("  Tokens: %d in / %d out\n", result.TokensIn, result.TokensOut)
	fmt.Println()
	fmt.Println("Generated files:")
	for _, f := range result.GeneratedFiles {
		fmt.Printf("  - %s\n", f)
	}

	return nil
}

// updateAgentsWithSpecsRef appends specs file references to AGENTS.md if not
// already present. The list of files is derived from the active SpecStandard,
// so adding a new standard with different artifacts does not require editing
// this function.
func updateAgentsWithSpecsRef(fromContextPath string, locale string, standard domainservice.SpecStandard, featureID string) error {
	agentsPath := filepath.Join(fromContextPath, "AGENTS.md")

	content, err := os.ReadFile(agentsPath)
	if err != nil {
		// AGENTS.md might not exist — skip silently
		return nil
	}

	// Check if specs reference already exists (idempotent)
	if strings.Contains(string(content), "specs/") {
		return nil
	}

	specsRef := sdd.SpecsReferenceSection(locale, standard, featureID)
	updated := string(content) + specsRef
	return os.WriteFile(agentsPath, []byte(updated), 0o644)
}
